// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// OnionServiceListerExpansion allows custom methods to be added to
// OnionServiceLister.
type OnionServiceListerExpansion interface{}

// OnionServiceNamespaceListerExpansion allows custom methods to be added to
// OnionServiceNamespaceLister.
type OnionServiceNamespaceListerExpansion interface{}
