// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kragniz/tor-controller/pkg/client/clientset/versioned/typed/tor/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeTorV1alpha1 struct {
	*testing.Fake
}

func (c *FakeTorV1alpha1) OnionServices(namespace string) v1alpha1.OnionServiceInterface {
	return &FakeOnionServices{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeTorV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
