// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kragniz/tor-controller/pkg/apis/tor/v1alpha1"
	scheme "github.com/kragniz/tor-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OnionServicesGetter has a method to return a OnionServiceInterface.
// A group's client should implement this interface.
type OnionServicesGetter interface {
	OnionServices(namespace string) OnionServiceInterface
}

// OnionServiceInterface has methods to work with OnionService resources.
type OnionServiceInterface interface {
	Create(*v1alpha1.OnionService) (*v1alpha1.OnionService, error)
	Update(*v1alpha1.OnionService) (*v1alpha1.OnionService, error)
	UpdateStatus(*v1alpha1.OnionService) (*v1alpha1.OnionService, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.OnionService, error)
	List(opts v1.ListOptions) (*v1alpha1.OnionServiceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OnionService, err error)
	OnionServiceExpansion
}

// onionServices implements OnionServiceInterface
type onionServices struct {
	client rest.Interface
	ns     string
}

// newOnionServices returns a OnionServices
func newOnionServices(c *TorV1alpha1Client, namespace string) *onionServices {
	return &onionServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the onionService, and returns the corresponding onionService object, and an error if there is any.
func (c *onionServices) Get(name string, options v1.GetOptions) (result *v1alpha1.OnionService, err error) {
	result = &v1alpha1.OnionService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("onionservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OnionServices that match those selectors.
func (c *onionServices) List(opts v1.ListOptions) (result *v1alpha1.OnionServiceList, err error) {
	result = &v1alpha1.OnionServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("onionservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested onionServices.
func (c *onionServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("onionservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a onionService and creates it.  Returns the server's representation of the onionService, and an error, if there is any.
func (c *onionServices) Create(onionService *v1alpha1.OnionService) (result *v1alpha1.OnionService, err error) {
	result = &v1alpha1.OnionService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("onionservices").
		Body(onionService).
		Do().
		Into(result)
	return
}

// Update takes the representation of a onionService and updates it. Returns the server's representation of the onionService, and an error, if there is any.
func (c *onionServices) Update(onionService *v1alpha1.OnionService) (result *v1alpha1.OnionService, err error) {
	result = &v1alpha1.OnionService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("onionservices").
		Name(onionService.Name).
		Body(onionService).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *onionServices) UpdateStatus(onionService *v1alpha1.OnionService) (result *v1alpha1.OnionService, err error) {
	result = &v1alpha1.OnionService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("onionservices").
		Name(onionService.Name).
		SubResource("status").
		Body(onionService).
		Do().
		Into(result)
	return
}

// Delete takes name of the onionService and deletes it. Returns an error if one occurs.
func (c *onionServices) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("onionservices").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *onionServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("onionservices").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched onionService.
func (c *onionServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.OnionService, err error) {
	result = &v1alpha1.OnionService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("onionservices").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
